### ISSUE TITLE
Document upload process to Lambda

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-sendgrid-event-proxy#2]
@philbooth could you explain how you uploaded the cloud function to @brizental ?

**Comment by vladikoff** [comment]
Did you manually zip the directory after `npm install` ?

**Comment by philbooth** [comment]
Yep, so it was a while ago but from memory it went something like this:

1. Zip up the directory, including `node_modules`.
2. Create a new Lambda function. Upload your zip.
3. Assign it roles to access CloudWatch Logs and SQS (obviously you need to use the same SQS queue URLs that you've got in local config).
4. Set environment variables to point Lambda at those same SQS queues.
5. Set an environment variable to enable authentication, because we don't want to leave an open webhook for anyone to send us bounce notifications through.
6. Create an API Gateway trigger for Lambda. Configure Sendgrid/SocketLabs to use that URL for the webhook.

Config should look something like this at the end:

<img width="1281" alt="Screenshot showing AWS Lambda config for fxa-sendgrid-event-prxy" src="https://user-images.githubusercontent.com/64367/43510256-fd421898-956c-11e8-9e19-a9066152d8c2.png" />

If you want to see my working Lambda/API Gateway pair, they're these:

* https://console.aws.amazon.com/lambda/home?region=us-east-1#/functions/fxa-sendgrid-event-proxy?tab=graph
* https://us-east-1.console.aws.amazon.com/apigateway/home?region=us-east-1#/apis/f29qym1r6a/resources/gzr75d/methods/ANY

I seem to remember having a bunch of problems getting it all hooked up and the thing that really helped was being able to test at each of the different layers, to identify where the problem was. So I recommend:

1. Unit tests in the repo to prove the core logic works.
2. Up in the top-right corner of the Lambda page there is a dropdown where you can create static test data and verify it's working inside Lambda (it's called `SendgridCatFacts` in mine if you want to go look at it).
3. Then Sendgrid itself had a test mechanism where I could plug in the API gateway URL and throw data at it to make sure it's working from there.
4. And lastly of course, testing end-to-end by sending an email through the email service and waiting for the delivery notification to show up in the queue process.

The other thing that I remember being non-trivial was correctly configuring CloudWatch so that I could view the logs when debugging the above. But that may have just been ineptitude on my part, think I was expecting it to just work and didn't realise I'd have to go in and manually create a log stream etc.

Hope that helps @brizental! Any questions or if you get stuck, give me a shout!

**Comment by philbooth** [comment]
In terms of the code, if you guys are doing it in this repo, Lambda makes it quite straightforward to have multiple entrypoints in the same script. So we could actually have the same zip bundle uploaded to both Lambdas if we wanted, and just set the entrypoint to be different in each one.

I mean the handler textbox, bottom right in this screenshot:

<img width="1288" alt="Screenshot of the AWS Lambda settings for fxa-sendgrid-event-proxy" src="https://user-images.githubusercontent.com/64367/43511213-c6025e1c-956f-11e8-8e5e-7135b90f5c8c.png" />

If we rename my `main` function to `sendgrid`, you could create a `socketlabs` function and just plug `index.socketlabs` in there instead.

(then you'd get the benefit of re-using the authentication and sqs-sending code, if you wanted)
